engines:
  bundler-audit:
    enabled: false
  csslint:
    enabled: true
  coffeelint:
    enabled: false
  eslint:
    enabled: false
  fixme:
    enabled: true
  rubocop:
    enabled: true
  brakeman:
    enabled: false
    exclude_fingerprints:
    - 0a616a63f4f81f91e6cd422960070286
  duplication:
        enabled: true
        config:
          languages:
          - ruby
          - javascript
ratings:
  paths:
  - Gemfile.lock
  - "**.css"
  - "**.coffee"
  - "**.js"
  - "**.jsx"
  - "**.rb"
exclude_paths:
- config/**/*
- db/**/*
- features/**/*
- script/**/*
- spec/**/*
- vendor/**/*
- "**.scss"
