engines:
  rubocop:
    enabled: true
  golint:
    enabled: false
  gofmt:
    enabled: false
  eslint:
    enabled: false
  csslint:
    enabled: false
  brakeman:
    enabled: true
ratings:
   paths:
   - "**.rb"
exclude_paths:
- "Cookbook/**/*"
# test
