# Save as .codeclimate.yml (note leading .) in project root directory
languages:
  Ruby: true
  JavaScript: true
exclude_paths:
- "app/models/micropost.rb"
- "sample_app_rails_4/app/assets/javascripts/**.js"
